version: '3.9'
services:
  scanner:
    image: ccion/lan-scanner:latest   # 直接从 Docker Hub 拉取
    container_name: lan-scanner
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./data:/data
    restart: unless-stopped
